import '../globals.css'

export const metadata = {
	title: 'Inti Web',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body suppressHydrationWarning={true}>{children}</body>
		</html>
	)
}
