import Footer from './components/modules/Footer'
import Navbar from './components/modules/Navbar'
import '../globals.css'
import { Outfit, Source_Sans_Pro } from 'next/font/google'

const outfit = Outfit({
	subsets: ['latin-ext'],
	variable: '--font-outfit'
})

const sourceSansPro = Source_Sans_Pro({
	display: 'swap',
	subsets: ['latin-ext'],
	weight: ['400', '600', '700', '900'],
	variable: '--font-source-sans-pro'
})

export const metadata = {
	title: 'Inti Web',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className={`${outfit.variable} ${sourceSansPro.variable}`}>
			<body suppressHydrationWarning={true}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	)
}
